### ISSUE TITLE
Feature request:force write

### ISSUE THREAD

**Issue by PrzemoF** [dfandrich/gpscorrelate#11]
Please add switch to force write gps info. I have photos with partially incorrect data and i need to strip the data first. Stripping is vary slow - I'm not sure why.

**Comment by PrzemoF** [comment]
I just discovered the command line version - feel free to ignore the request

**Comment by dfandrich** [comment]
Ver. 2 now offers the "Replace existing tags" option. Does that not do what you
expect?
