### ISSUE TITLE
Possible Bug: About Menu missing icon/splash

### ISSUE THREAD

**Issue by Saijin-Naib** [dfandrich/gpscorrelate#17]
![image](https://user-images.githubusercontent.com/19295950/139189742-4a02a59a-0cd8-473a-878d-906783ab63c4.png)
Taken from the current flatpak release, and verified by local build from source.

I tried editing the gui.c to point the gps-correlate icon to gps-correlate.svg, but that was not correct.

I am not sure what the proper fix is to get the icon/splash to draw on the About screen.

**Comment by Saijin-Naib** [comment]
So, it turns out this is a symptom of not building/installing the ```install-desktop-file``` make target.

So, closing, and as an aside, this is now packaged for Alpine :)

**Comment by dfandrich** [comment]
That's probably worthwhile adding to INSTALL. Not all targets are mentioned
there. I'll do that before the next release.
