### ISSUE TITLE
Mention tremendous new need for this program due to new Dreamliner etc. airplanes that block GPS

### ISSUE THREAD

**Issue by jidanni** [dfandrich/gpscorrelate#19]
In the introduction you might mention that the chief use of this program
might have been for back when cameras didn't have GPS, and one
didn't own a cellphone.

But it turns out there will be an enormous new "market" for this
program: Due to electrostatic adjustable tinted glass, there is alas no
more GPS signal penetrating newer airliners like Boeing's Dreamliner.

Yes, window shades are out of style, and so is our precious GPS signal. 

Yup, the only way to put the coordinates back into the EXIF's on all
those pictures you took of the Aleutian Islands is to (within one week
of landing, else pay) go to e.g., the FlightAware website, download the KMLs, and
convert via gpsbabel to GPX, and then use them in this program!

**Comment by dfandrich** [comment]
That's an interesting use case and might be worth mentioning. Now that pro level DSLR all seem to have built-in GPS and point-and-shoot cameras are going away, there aren't a lot of cameras left that don't geotag photos already.

**Comment by dfandrich** [comment]
Added a mention as part of commit #965ad0a3
