### ISSUE TITLE
Support HEIC

### ISSUE THREAD

**Issue by jidanni** [dfandrich/gpscorrelate#20]
My Samsung phone saves twice as much space as .JPG with .HEIC. Alas only https://github.com/exiftool/ supports that. (It also has [-geotag](https://exiftool.org/geotag.html)...).

**Comment by dfandrich** [comment]
gpscorrelate relies on libexiv2 to perform image data manipulation, so it needs to wait for that support. exiv2 version 0.27.4 added read-only support, but it looks like write support isn't there yet. Once that happens, it should work automatically in gpscorrelate.
