### ISSUE TITLE
Test failure: test005

### ISSUE THREAD

**Issue by sikmir** [dfandrich/gpscorrelate#29]
Test expects:
https://github.com/dfandrich/gpscorrelate/blob/dba4adef404957a3d9c3a44cb7eea48a24cb9ba3/tests/data/test005.result#L1

But actual output is:
```sh
I/O warning : failed to load "does-not-exist": No such file or directory
```

**Comment by dfandrich** [comment]
Looks like libxml2 changed their wording. What version are you using?

**Comment by sikmir** [comment]
> Looks like libxml2 changed their wording. What version are you using?

2.13.3

**Comment by dfandrich** [comment]
That's the latest version. I'll adjust the test to work.
