### ISSUE TITLE
Where to get download link?

### ISSUE THREAD

**Issue by sergentum** [dfandrich/gpscorrelate#3]
I can't find anywhere link to bin file. Is it exists?

**Comment by dfandrich** [comment]
I haven't done a release yet since taking over maintainership, but when I do it will only be a source release (tar balls) and not executable binaries. I'm hoping to do a release soon.

**Comment by sikmir** [comment]
@dfandrich Could you please make a release? Many [packages repositories](https://repology.org/project/gpscorrelate/versions) still use 1.6.1 and can't switch from freefoote/gpscorrelate as far as no stable release yet.

**Comment by dfandrich** [comment]
I've just made a new release. The stable link to find latest release is https://github.com/dfandrich/gpscorrelate/releases/latest
