### ISSUE TITLE
Closure of the application to the execution of the correlation

### ISSUE THREAD

**Issue by Jrachi-2** [dfandrich/gpscorrelate#5]
It has been happening for a few days. I imagine after a kernel upgrade or attached libraries.
After assigning one or more images and opening a gpx file, pressing the "Correlate Photos" button causes the application to close unexpectedly.
The same happens by pressing "Strip GPS tags"
Selecting "Don't write" the correlation happens regularly, I see that on the left the data on the position are inserted. But if I uncheck the "Don't write" box and press "Correlate Photos" the application closes without changes to the files.
Below info on my system.
Ciao

Operating System: KDE neon 5.16
KDE Plasma Version: 5.16.3
KDE Frameworks Version: 5.60.0
Qt Version: 5.12.3
Kernel Version: 4.15.0-55-generic
OS Type: 64-bit
Processors: 12 × Intel® Core™ i7-4930K CPU @ 3.40GHz
Memory: 15,6 GiB

**Comment by Jrachi-2** [comment]
I tried to use the command line ...
This is the result:
`ivo@Criceto:/media/ivo/SdA/jpg 1/2019/2019-07-27 TC - Monti - Mezzenile$ gpscorrelate -v -O-7129 -g gpx.gpx *.JPG
EXIF-GPS Photo matching program.
Daniel Foote, 2005.

Reading GPS Data...

Correlate: 
terminate called after throwing an instance of 'Exiv2::BasicError<char>'
  what():  IMG_2967.JPG: Failed to open file (a+b): Permission denied (errno = 13)
Annullato
`
And:

`ivo@Criceto:/media/ivo/SdA/jpg 1/2019/2019-07-27 TC - Monti - Mezzenile$ sudo gpscorrelate -v -O-7129 -g gpx.gpx *.JPG
[sudo] password di ivo: 
EXIF-GPS Photo matching program.
Daniel Foote, 2005.

Reading GPS Data...

Correlate: 
IMG_2967.JPG: Exact match: Lat 45.275623, Long 7.375937, Elev 1148.930000.
IMG_2968.JPG: Exact match: Lat 45.275299, Long 7.374848, Elev 1156.520000.
IMG_2969.JPG: Interpolated: Lat 45.277352, Long 7.358660, Elev 1245.118333.
IMG_2970.JPG: Exact match: Lat 45.279446, Long 7.357216, Elev 1256.990000.
IMG_2971.JPG: Interpolated: Lat 45.279919, Long 7.357693, Elev 1265.590000.
IMG_2972.JPG: Interpolated: Lat 45.280115, Long 7.357683, Elev 1269.138182.
IMG_2973.JPG: Interpolated: Lat 45.281526, Long 7.356657, Elev 1316.216667.
IMG_2974.JPG: Interpolated: Lat 45.281525, Long 7.356668, Elev 1315.640000.
IMG_2975.JPG: Interpolated: Lat 45.281539, Long 7.356669, Elev 1315.760000.
IMG_2976.JPG: Exact match: Lat 45.281715, Long 7.356606, Elev 1318.250000.
IMG_2977.JPG: Interpolated: Lat 45.281725, Long 7.356605, Elev 1318.424545.
IMG_2978.JPG: Interpolated: Lat 45.282635, Long 7.356827, Elev 1297.128333.
IMG_2979.JPG: Interpolated: Lat 45.285173, Long 7.357357, Elev 1228.180000.
IMG_2980.JPG: Exact match: Lat 45.285763, Long 7.357365, Elev 1228.880000.
IMG_2981.JPG: Interpolated: Lat 45.285784, Long 7.357264, Elev 1229.365000.
IMG_2982.JPG: Interpolated: Lat 45.285817, Long 7.357229, Elev 1229.898571.
IMG_2983.JPG: Interpolated: Lat 45.285825, Long 7.357235, Elev 1230.076000.
IMG_2984.JPG: Interpolated: Lat 45.286044, Long 7.357268, Elev 1228.470000.
IMG_2985.JPG: Interpolated: Lat 45.286044, Long 7.357268, Elev 1228.470000.
IMG_2986.JPG: Interpolated: Lat 45.286044, Long 7.357268, Elev 1228.470000.
IMG_2987.JPG: Interpolated: Lat 45.286044, Long 7.357268, Elev 1228.470000.
IMG_2988.JPG: Interpolated: Lat 45.286493, Long 7.357333, Elev 1221.967059.
IMG_2989.JPG: Interpolated: Lat 45.286566, Long 7.358284, Elev 1195.512222.
IMG_2990.JPG: Interpolated: Lat 45.288803, Long 7.360261, Elev 1182.968889.
IMG_2991.JPG: Interpolated: Lat 45.288791, Long 7.360276, Elev 1183.017778.
IMG_2992.JPG: Interpolated: Lat 45.288806, Long 7.360417, Elev 1181.133333.
IMG_2993.JPG: Interpolated: Lat 45.288772, Long 7.360811, Elev 1177.215333.
IMG_2994.JPG: Interpolated: Lat 45.288139, Long 7.368364, Elev 1133.673077.
IMG_2995.JPG: Interpolated: Lat 45.286681, Long 7.369531, Elev 1130.296316.
IMG_2996.JPG: Interpolated: Lat 45.286708, Long 7.369769, Elev 1124.201364.
IMG_2998.JPG: Interpolated: Lat 45.286567, Long 7.372858, Elev 1096.662857.
IMG_2999.JPG: Interpolated: Lat 45.292894, Long 7.372449, Elev 1150.201429.
IMG_3000.JPG: Exact match: Lat 45.292896, Long 7.372460, Elev 1150.290000.
IMG_3001.JPG: Interpolated: Lat 45.293585, Long 7.380512, Elev 1125.979167.

Completed correlation process.
Matched:    34 (6 Exact, 28 Interpolated, 0 Rounded).
Failed:      0 (0 Not matched, 0 Write failure, 0 Too Far,
                0 No Date, 0 GPS Already Present.)
`
I tried to correlate some photos, which I had already processed with gpscorrelate a few days ago and the problem repeats itself. This is not a change of the file owner!

**Comment by dfandrich** [comment]
On Wed, Jul 31, 2019 at 03:35:25AM -0700, Jrachi-2 wrote:
This looks like a really, really old version. What does gpscorrelate -V say?
Whatever the problem is, there's a good chance it's been fixed since.

**Comment by Jrachi-2** [comment]
Sorry.
I use the version in the official repositories.

'Tivo @ Hamster: ~ / Downloaded / gpscorrelate-master $ gpscorrelate -v
EXIF-GPS Photo matching program.
Daniel Foote, 2005. '

I tried to install the latest version.
I received a lot of reports of misconduct.
Somehow the installation was successful and the version is now:



*ivo@Criceto:~/Scaricati/gpscorrelate-master$ gpscorrelate -vgpscorrelate,
ver. 1.6.2git. Daniel Foote, Dan Fandrich, 2005-2016. GNU GPLAt least one
image file name must be given.*

And it works properly.
Thank you very much

Il giorno mer 31 lug 2019 alle ore 13:52 Dan Fandrich <
notifications@github.com> ha scritto:

**Comment by dfandrich** [comment]
I'm overdue to make a new release. I'll try to do that soon.

**Comment by dfandrich** [comment]
I've just made a new release.
