### ISSUE TITLE
Add an about button ?

### ISSUE THREAD

**Issue by Binnette** [dfandrich/gpscorrelate#6]
Hi, thank you for this **excellent** software. I just downloaded it through my packet manager and it is working great and is really fast. Because i downloaded it through my package manager, i was unable to determine where is the bug tracker and the main software page.

Can you please consider adding an "about" button, that maybe show a popup that display: website url, git repo, bugtracker url, version, credits, library credit (if any), licence ?

Bye, have a nice day.

**Comment by dfandrich** [comment]
Good idea!
